src/save/Controllers/ItemsController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using save.Models;
using AutoMapper;
using System.Collections.Generic;
using System.Security.Claims;
using System;
using Microsoft.AspNetCore.Identity;
using save.Data;
using save.Models.ItemViewModels;
using save.Data.Repositories;
using save.Data.Interfaces;
using save.Services;

namespace save.Controllers
{
    public class ItemsController : Controller
    {
        private readonly UserManager<User> _userManager;
        private IItemRepository _itemRepository;
        private readonly IUserService _currentUser;

        public ItemsController(UserManager<User> userManager, IItemRepository itemRepository, IUserService currentUser)
        {
            _currentUser = currentUser;
            _itemRepository = itemRepository;
            _userManager = userManager;
        }

        // GET: Items
        public IActionResult Index()
        {
            string userID = _userManager.GetUserId(_currentUser.GetUser());
            List<ItemViewModel> list = _itemRepository.GetAllForUser(userID).ToList();
            return View(list);
        }

        // GET: /jfgk64
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                //Add search function here
                return RedirectToAction("Index");
            }

            string userID = _userManager.GetUserId(_currentUser.GetUser());
            ItemViewModel result = _itemRepository.GetSingleByID((int)id, userID);

            if (result == null)
            {
                return NotFound();
            }           

            return View(result);
        }

        // GET: Items/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Items/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ItemViewModel IVM)
        {
            string userID = _userManager.GetUserId(_currentUser.GetUser());
            if (ModelState.IsValid)
            {
                _itemRepository.Create(IVM, userID);
                return RedirectToAction("Index");
            }
            
            return View(IVM);
        }

        // GET: Items/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                //Add search here
                return RedirectToAction("Index");
            }
            string userID = _userManager.GetUserId(_currentUser.GetUser());
            ItemViewModel result = _itemRepository.GetSingleByID((int)id, userID);

            if(result == null)
            {
                return NotFound();
            }

            return View(result);
        }

        // POST: Items/Edit/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public IActionResult Edit(Item item)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _context.Update(item);
        //        _context.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    return View(item);
        //}

        //// GET: Items/Delete/5
        //[ActionName("Delete")]
        //public IActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    Item item = _context.Items.Single(m => m.Id == id);
        //    if (item == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(item);
        //}

        //// POST: Items/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public IActionResult DeleteConfirmed(int id)
        //{
        //    Item item = _context.Items.Single(m => m.Id == id);
        //    _context.Items.Remove(item);
        //    _context.SaveChanges();
        //    return RedirectToAction("Index");
        //}
    }
}

src/save/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] | Save-It</title>

        <environment names="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
            <link rel="stylesheet" href="~/lib/bootstrap-material-design/dist/css/bootstrap-material-design.css" />
            <link rel="stylesheet" href="~/lib/bootstrap-material-design/dist/css/ripples.css" />
            <link rel="stylesheet" href="~/dist/css/main.css" />
        </environment>
        <environment names="Staging,Production">
            <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
            <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        </environment>
    </head>
    <body>
        <div class="header-bar navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-controller="Home" asp-action="Index" class="navbar-brand">Save-It</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a asp-controller="Items" asp-action="Create">Create new item</a></li>
                        <!--<li><a asp-controller="Home" asp-action="About">About</a></li>
                        <li><a asp-controller="Home" asp-action="Contact">Contact</a></li>-->
                    </ul>
                    @await Html.PartialAsync("_LoginPartial")
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer class="text-center">
                <p>&copy; 2016. Save-It</p>
            </footer>
        </div>

        <environment names="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/lib/bootstrap-material-design/dist/js/material.js"></script>
            <script src="~/lib/bootstrap-material-design/dist/js/ripples.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
            <script>$(function () {$.material.init();});</script>
        </environment>
        <environment names="Staging,Production">
            <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery">
            </script>
            <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
            </script>
            <script src="~/js/site.min.js" asp-append-version="true"></script>
        </environment>

        @RenderSection("scripts", required: false)
    </body>
</html>